### ISSUE TITLE
Provide an error message when user tries to download a raster in catalog when not logged in

### ISSUE THREAD

**Issue by joeriverheijden** [nens/lizard-catalogue#110]
PR:
https://github.com/nens/lizard-catalogue/pull/182
https://github.com/nens/lizard-catalogue/pull/183
https://github.com/nens/lizard-catalogue/pull/184

Currently, when a user tries to download a rasters via the catalogue when not logged in, the progress bar remains empty. Leading to infinite waiting time of users. Users can't download a raster when not logged in so we should provide a message and guiding that the user has to login first.

The message can be:
'Whoops! Please login first so we can get your request ready!'

![91b3d217-c3c5-41ab-b271-2a7647e6080e.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/eab1a994-d14d-4ce5-bc6a-a024b22ec162)

**Comment by Derryrover** [comment]
@joeriverheijden 

Hi Joeri,

I have the following remarks:

**Reproduce succesfull**
I reproduced the problem:
When the user attempts to download something while being not logged in the download does not proceed.

**Proposed solution seems not ideal**
If I assume that only logged in users may download then the solution proposed about showing an error message while downloading is still not ideal.
Namely the user is notified way to late that downloading is not possible. The user now has to:
- close the download popup (user looses the grid selection it made, maybe making the grid selection took user a lot of time)
- Go to login and get redirected (user looses the search results and the raster it selected, user now has to look for the raster again)

**New proposed solution?**
I think we can make it more comfortable to the user by:
- disabling (greying out) the export buttons already as soon as the user selected the raster /wms. 
Hoovering over the button will show the text "please login to download".
- See if we can make the sso redirect to the precise url of the current selected raster/wms. Currently the sso redirects to /catalogue. The selected raster of the user is thus forgotten. We could instead redirect the login to the complete url postfix (for example "/catalogue/?data=Raster&uuid=03d36a02-54a0-4f2f-95a9-db4592e3dcb1")

What do you think?

kr Tom

**Comment by lexvand** [comment]
@Derryrover 
In absence of Joeri, let me decide on this. I think your proposal is indeed better. The second bullet is more a nice-to-have though. Don't know how difficult it is to make it that way...?

**Comment by Derryrover** [comment]
@lexvand 
If the second bullet is hard we will skip it. I think it is a oneliner

**Comment by Derryrover** [comment]
@lexvand 
@joeriverheijden 

Hi Lex and Joeri,

Regarding catalogue disable export when not logged in:
Could you have a look if this is as desired?
https://nxt3.staging.lizard.net/catalogue/

Had to test this on staging.
Therefore I needed to already merge and deploy to staging.
- The lizard-sso now redirects back to the selected raster on login
- The export button is disabled with tooltip "login to export" when user is not logged in.

Optionally to do?: When user logs out, she is not redirected by sso to selected raster (on login this does work). Please let me know if you like me to implement that.

kr Tom

**Comment by lexvand** [comment]
Looks good and works as desired. Just need to add a white space in the hover text: "Log in to export".

**Comment by Derryrover** [comment]
@lexvand 

Okey done:
- fixed typo log in
- while I was busy anyway, I also made the selected raster remembered on logout. (If logged out user does not have rights to see that raster then detail view shows blank)

Deployed to staging again.


Shall I deploy to production?
Current production version is 0.1.40
The only changes since then are from this ticket:
https://github.com/nens/lizard-catalogue/releases

**Comment by lexvand** [comment]
Test successful. Please contact @joeriverheijden before production release as this may have to be communicated.

**Comment by Derryrover** [comment]
Deployed 0.1.43 to production and verified works
