### ISSUE TITLE
Refactor the Lizard Catalogue

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-catalogue#154]
<ul>
	<li>Did we consider placing the state regarding the filters in the redux store?
	<ul>
		<li>I see now that at least some parts (like checked radio buttons) are actually in the redux store, but that they are duplicated in the react state. ->> remove checked radio button and keep all selected filters in the Redux store (<a href="https://nelen-schuurmans.atlassian.net/browse/FRNT-563" title="smart-link" class="external-link" rel="nofollow noreferrer">https://nelen-schuurmans.atlassian.net/browse/FRNT-563</a> )</li>
	</ul>
	</li>
	<li>Did we consider making the following flow more dry? There seems to be a lot of code duplicate :  updating filterstate → updating url → fetching new data → updating state with new data ->> Improve the flow under ticket: <a href="https://nelen-schuurmans.atlassian.net/browse/FRNT-563" title="smart-link" class="external-link" rel="nofollow noreferrer">https://nelen-schuurmans.atlassian.net/browse/FRNT-563</a>
	<ul>
		<li>Some very good things I see here is that functions like “newUrl()” are already factored out, but we may experiment if it is possible to refactor even more. Was this attempted yet that you know of?</li>
		<li>Note that the previous point regarding the redux store may also play a role in refactoring this.</li>
	</ul>
	</li>
	<li>Did we consider making seperate components from organisationfilter, observationtypefilter, datafilter?</li> --> done in this PR: https://github.com/nens/lizard-catalogue/pull/197
	<li>We should make the basket a seperate component (<a href="https://nelen-schuurmans.atlassian.net/browse/FRNT-532" title="smart-link" class="external-link" rel="nofollow noreferrer">https://nelen-schuurmans.atlassian.net/browse/FRNT-532</a> )</li>
	<li>We should make the profile dropdown a seperate component</li>
        <li>Refactor raster details, wms details and monitoring network details to one reusable component</li>
        <li>Refactor raster list, wms list and monitoring network list to one reusable component</li>
        <li>Refactor table in the list component to use css table instead of flex box</li>
</ul>

<p>Added by Hoan:</p>

<ul>
	<li>Refactor the Raster/WMS list by making separate components for the search bar and the footer (including the pagination bar) so they can be reused by both the Raster and the WMS layer list (<a href="https://nelen-schuurmans.atlassian.net/browse/FRNT-545" title="smart-link" class="external-link" rel="nofollow noreferrer">https://nelen-schuurmans.atlassian.net/browse/FRNT-545</a> ) - DONE</li>
</ul>

<i>[FRNT-526] created by tom.deboer</i>

**Comment by hoanphungt** [comment]
Most of the things mentioned above have been done so I close this issue.
