### ISSUE TITLE
Table overlaps its header

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-catalogue#178]
<p> <span class="image-wrap" style=""><a id="10604_thumb" href="/secure/attachment/10604/10604_image-2020-02-06-11-07-51-350.png" title="image-2020-02-06-11-07-51-350.png" file-preview-type="image" file-preview-id="10604" file-preview-title="image-2020-02-06-11-07-51-350.png"><jira-attachment-thumbnail url="https://nelen-schuurmans.atlassian.net/secure/thumbnail/10604/image-2020-02-06-11-07-51-350.png?default=false" jira-url="https://nelen-schuurmans.atlassian.net/secure/thumbnail/10604/image-2020-02-06-11-07-51-350.png" filename="image-2020-02-06-11-07-51-350.png"><img src="https://nelen-schuurmans.atlassian.net/secure/thumbnail/10604/image-2020-02-06-11-07-51-350.png" data-attachment-name="image-2020-02-06-11-07-51-350.png" data-attachment-type="thumbnail" data-media-services-id="a6c79945-70fb-4b53-8065-d08804f098c2" data-media-services-type="file" style="border: 0px solid black" /></jira-attachment-thumbnail></a></span> </p>

<p>Headers partly fall behind the table itself. Description is also lined out differently.</p>
<i>[FRNT-697] created by lex.vandolderen</i>

**Comment by hoanphungt** [comment]
@lexvand 
I think this is no longer the case after the recent releases
