### ISSUE TITLE
Details of monitoring network

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#189]
Details of monitoring networks including:

- description
- map with locations?
- List of observation types
- Select timeseries action

Work flow:

- API call to get information of a measuring network
- Update Redux store with the information
- Show the information in the detail view
- Make map with locations of timeseries?
- Other relevant information
- Select timeseries action

**Comment by hoanphungt** [comment]
@lexvand 
The timeseries endpoint only contains url of its location. So for a measuring network of ~1000 timeseries, I would need to make ~1000 api calls to retrieve their location data at the same time. So definitely not good. 

I think it would be nice to either:

- Include the location data in the timeseries response. This is the most straightforward way.

- Or as suggested by Casper in https://github.com/nens/lizard-nxt/issues/3694#issuecomment-673334336 to have a monitoring network filter on the location response. This way I can retrieve all locations belong to 1 monitoring network easily.

**Comment by lexvand** [comment]
@hoanphungt 
I think we have good reasons to make the timeseries endpoint less bloated, so I agree with Casper that it is more elegant to add a montoring network filter on the location endpoint.

Next question is what more the catalogue requires to function well after drawing the locations on the map. Can we properly relate the timeseries within the network with the locations requested based on the network filter. Or are we running into trouble with any additional timeseries that belong to the selected locations, but not to the network? That's not entirely clear to me.

**Comment by hoanphungt** [comment]
@lexvand 
I think it shouldn't be the case though, because the location doesn't contain any information about the timeseries. So any additional timeseries that do not belong to the network would not be included. I think I can relate the timeseries within the network with the right location in this case then.
