### ISSUE TITLE
Multiple selection in filter bar

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#204]
Currently, filter bar in the Catalogue only supports one selection at a time so a radio button is chosen. If multiple filter of organisations/observation types/datasets on raster/wms layer/monitoring network is available, we need to update how the filter works and switch to checkboxes instead of radio button.

To Do:

- [x] Check if multiple organisations can be added to filter of rasters/wms layers/monitoring networks --> multiple organisations can be selected using their UUIDs: `organisation__uuid=uuid1,uuid2,uuid3`
- [x] Check if multiple datasets can be added to filter of rasters/wms layers --> multiple datasets can be selected using `datasets__slugs=slug1,slug2`
- [x] Check if multiple observation types can be added to filter of rasters --> not possible to have multiple selection

- [ ] Change radio button to checkbox for multiple selection

**Comment by hoanphungt** [comment]
@joeriverheijden @LirryPinter 
Hi Joeri and Lirry,

As in the description, for the filters of rasters/wms layers/monitoring networks in the catalogue, I checked and it is now possible by backend to filter by multiple **organisations** and/or multiple **datasets**. It's not possible to do so with **observation type** though. Could you confirm if you would want to enable this feature for the catalogue? It would require some changes and probably cost around 1 day.

**Comment by hoanphungt** [comment]
@lexvand 
Hi Lex,

Although this issue is made by me and the multiple filters are supported by backend for organisation and dataset fields, I think it's quite risky to change the way the filter bar currently works and don't recommend to do it now if it is not something that can really improve the catalogue. There are a few reasons for it:

- The state of the filter bar is stored in the Redux store to keep the filter values and the URL queries in sync with each other. Changing this part will take quite sometimes.
 
- The design for the filter bar needs to be updated in case of multiple selection. Otherwise, we could have a long list of selected filters under the search bar (for example: `x Aa en Hunze` `x Nelen & Schuurmans` ...). This is for users to easily remove their previous filter selection but it will break the current layout.

- The component that renders the different filter options (which currently support single selection) will need to be refactored to adapt to the multiple selection.

So overall, I think if this is not something that we desperately want for the catalogue then we put it to the ice box and spend time on other topics (the alarm and timeseries management page and timeseries selection modal in the catalogue). Otherwise, if we really want to have this multiple selection, I re-estimate about 3 - 4 story points to complete it.

Please let me know what you think.

Kr, Hoan

**Comment by lexvand** [comment]
@hoanphungt Alright, that was not clear to me. It sounded like a nice feature which was not too complicated. I removed it from the sprint.

**Comment by hoanphungt** [comment]
@lexvand 
Yes, I underestimated it. I think it would be best to pick it up if we have some free time during sprints that are not busy and along with some refactoring for some parts of the catalogue. I will keep it in mind.
