### ISSUE TITLE
Polygon selection of locations in timeseries selection modal

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#205]
According to design: https://xd.adobe.com/view/42a1c54f-2241-4240-b933-fb5ea4aaa18a-17f2/screen/6fc5567e-2faa-4759-9a4e-5312dd9b5ad7/, there is a polygon icon in the right bottom corner of the map to select multiple locations at once. 

Discuss if this feature is desirable and if everything is clear about how it should work and if the API supports this feature.

To Do:

- [x] Check with Lirry and Joeri if this feature is still desirable

- [x] Check with Lirry if the requirement is clear

- [x] Check with Casper/Carsten if API supports this feature fully

- [x] Research the technology to use for the polygon selection: use `Leaflet Polygon` to draw polygon and a small npm module called `point-in-polygon` to determine locations within the polygon.

**Comment by hoanphungt** [comment]
@LirryPinter 
Hi Lirry,

What do you think about the color for the polygon layer:
<img width="1216" alt="polygon" src="https://user-images.githubusercontent.com/43402556/93216939-a380ad00-f768-11ea-93a5-fd2e7c8b4434.png">

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Would you have time to review this polygon selection ticket: https://github.com/nens/lizard-catalogue/pull/213?

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 
@LirryPinter 

Hi Hoan and Lirry,

Regarding selecting locations for timeseries:

@hoanphungt: Hoan I reviewed your branch, looks mostly good. One technical comments in pr.

@LirryPinter: Are you 100% sure about the trashbin icons? They are by convention for deleting, not de-selecting.

kr Tom

**Comment by LirryPinter** [comment]
@Derryrover @hoanphungt 

Although I do not really agree on that (there are cases where this is used), we can also use this:
![image](https://user-images.githubusercontent.com/44164164/93328219-bf915680-f81b-11ea-82fc-e92564e57048.png)
With the left for the normal state an the right for the hovered one. 

If you guys think this is better let me know, then ill update the design

**Comment by Derryrover** [comment]
@LirryPinter 
@hoanphungt 
I was thinking a simple x icon, but this minus-icon looks probably even better !
Hoan, What do you think?

**Comment by LirryPinter** [comment]
@hoanphungt @Derryrover 
Updated design

**Comment by hoanphungt** [comment]
Looks good to me :) thanks for the comments

**Comment by hoanphungt** [comment]
@LirryPinter 
Hi Lirry,

Currently, lizard catalogue is using font awesome library for icons. However, it only has the minus-circle icon in hover state but not in normal state. It does have the minus-square icons in both state though. This is how it looks like when using minus-square instead of minus circle, what do you think about this alternative?

<img width="778" alt="Screenshot 2020-09-16 at 22 01 01" src="https://user-images.githubusercontent.com/43402556/93386587-348a7d80-f868-11ea-86db-2bba0c6eeb22.png">

**Comment by LirryPinter** [comment]
@hoanphungt 

Yes that is fine!

**Comment by hoanphungt** [comment]
Merged after adding the deselecting icon and fixed code reviewed by Tom
