### ISSUE TITLE
Improve styling of scroll bars

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#206]
Joeri wishes to have a nice scroll bar in the Catalogue just like the scroll bar in iphone ...

A good example is the scroll bar that we used in the lizard management client.

Places to add the new scroll bar in the Catalogue:

- [x] Filter bar
- [x] Details column
- [x] Description in details column
- [x] Selected items in basket
- [x] Selected locations in time series selection modal

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Joeri wishes to have a nice scroll bar for all the scrollable places in the Catalogue. Do you think the `react-custom-scrollbars` library that we used for the lizard-management-client is a good solution for this issue? How was your experience using this library?

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 
@joeriverheijden 
@LirryPinter 

Hi Hoan, Lirry and Joeri,

Above is the question if I recommend a custom scrollbar component.
I didnot have a lot of experience with the react-custom-scrollbars, but I do not recall any severe problems while using it.
Anyway, as techlead of the client, I must recommend against using such a tool.
This is a recommendation so of course if we really want it badly we can still use it.
The react scrollbar component has the advantage over a css solution that it will look similar pretty across browsers.

So why do I recommend against react-custom-scrollbars (and any other custom scrollbar component) ?

- The scollbar is a standard browser widget. Using anything that deviates from the standard will create more work. **We should attempt to style the scrollbar with css instead** (even if this is not in all browsers supported)

- I agree that a custom scrollbar will look nicer and more consistent across browsers. But it is very unlikely that our users will say: "I am not using this app because it has an ugly scrollbar". At the moment I feel like we have more urgent matters then polishing. We are still in the foundation phase.

- We should be able to add the custom scrollbar lateron. If that is not a trivial matter, then that is a red flag to me.

kr Tom

**Comment by LirryPinter** [comment]
@hoanphungt 
@Derryrover @joeriverheijden 

Hi,

There is already a custom scrolling bar in the management like this:
![image](https://user-images.githubusercontent.com/44164164/93739490-b1ab4f00-fbe8-11ea-8612-e0d58b3a388d.png)
Can you explain to me the problem to implement this scrollbar in other places? Or is this actually already done through CSS? 

About your comment about the users:
![image](https://user-images.githubusercontent.com/44164164/93739599-fafb9e80-fbe8-11ea-960c-102ba15460ae.png)
We make software with a lot of stuff going on. There needs to be a lot in a screen and it is already a challenge to keep enough white space. White space is important in design, and yes users do not like screen full with elements close to each other. So if we can save space and have nice scrollbars this something to spend a bit time on, wont you agree?

**Comment by Derryrover** [comment]
@LirryPinter 
Yes the custom scrollbar component mentioned above is currently in the management client.
It is a react component library (not made by us), and I did not lookup how it is implemented by that component library.
I just think a a scrollbar should preferably not be implemented by a component by the reasons stated above.
A css only solution btw would not work on ubuntu with firefox (just tested this), so this library has at least some "magic" going on.

I am not sating this is all bad. It is more that all this kind of things together likely are going to cost you more (time,money) then it will bring. It is likely the best to stick as close to the standards as possible. Libraries like these are often created by individuals in their freetime. The standard scrollbar is maintained by a team of paid professionals. 

It is not hard to use the custom scrollbar and will cost in the beginning not a lot more time.
But adding a lot of this sort of things to a project increases the risk of costing a lot more time on the long run.

**Comment by LirryPinter** [comment]
@Derryrover 

"Libraries like these are often created by individuals in their free time". I understand it is a risk to use custom components made by others, but sometimes they are good and in this case I would argue that making it yourself would indeed take too much time and money. 
https://github.com/malte-wessel/react-custom-scrollbars
This is the library we are using. The repo is starred by 2.6k people, and this guy is a professional working at trivago. Do you think this is a risky library and you can make it better?

Anyway, maybe we should stop arguing about this and let @joeriverheijden or @lexvand make a decision about this

**Comment by LirryPinter** [comment]
@Derryrover 

Oh yeh and it is downloaded 500.000 times every month, so its getting pretty close to a 'standard' I would say..

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Would you like to review this PR: https://github.com/nens/lizard-catalogue/pull/238? I restyled the scrollbar using css only. Let's see if it is good enough.

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Yes works both on firefox and chrome!
In my opinion this is definitely good enough and way better then importing some library for this.

Ready to merge

**Comment by GeOdin** [comment]
@hoanphungt 

Hey Hoan :)

It looks nice! :)

I checked the Details column and description therein for the raster LiDAR banken and Regen (ad5bfe0f-6286-4576-8eaa-fbcf21d5ee82) (amongst others).
The basket also looks nice.

Is it true that with filter bar, you meant the filter observation type scrolldown? I saw that the scrolldown still looked like the old scrollbar. It could also be that I am mistaking the filter scrollbar for something else. I will post a screenshot below:

![20210113-catalogue-staging-scrollbar-whole-page-1366-768-resolution-filter-bar-observation-scrollbar.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/4a2ee0ec-a14d-43e9-b744-88dcf4c93895)

I was wondering, would it also be possible to style the scrollbar for the whole page in the same way or remove it in some way?
I am testing on 1366x768 (most used resolution according to Lirry) and there the scrollbar for the whole page still looks like the standard version. On Chrome, FireFox and Edge.

![20210113-catalogue-staging-scrollbar-whole-page-1366-768-resolution.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/3659671f-4921-4f71-9394-505084148e98)

Kind regards,
Madeleine

@lexvand 

Hey Lex :)
I only have the 'Large N&S Sample' and 'KNMI All' timeseries in the catalogue on staging.
They both only have 2 locations, so there are not enough locations for me to test the scrollbar.
Do you know of a timeseries that has more locations on staging, so I can test that part better?

Kind regards,
Madeleine

**Comment by hoanphungt** [comment]
@GeOdin 
Hi Madeleine,

Thanks for your comments. 

For the filter bar, i meant the filter bar on the left side of the catalogue (filters for organisations, observation types and datasets). The scrollbar only appears when you click on "...more" at the end of the filter. The other scrollbar that appears in the dropdown for the observation types in the timeseries modal is default scrollbar of browser. It doesn't take up white-space of the whole page so I think it's ok to have it like that (also it might be tricky to change the scrollbar of a dropdown element).

For the scrollbar of the whole page, I didn't notice it. I will take a look. Thanks for your finding.

Kr, Hoan

**Comment by lexvand** [comment]
@GeOdin Large N&S Sample has a lot more locations. Check your rights.

**Comment by GeOdin** [comment]
@hoanphungt 

Hey Hoan :)

The filter bar scrollbar also looks nicely. :)
