### ISSUE TITLE
Make filter for observation type "searchable" in time series selection modal 

### ISSUE THREAD

**Issue by joeriverheijden** [nens/lizard-catalogue#209]
When a monitoring network contains a 1000 observation types, the current design becomes unusable. To make it usable a searchbar for observation types is needed. 

@LirryPinter can you already incorporate this in a design? Design: https://xd.adobe.com/view/42a1c54f-2241-4240-b933-fb5ea4aaa18a-17f2/screen/dfa6c937-94a2-46ee-b452-6392908e42b2/
@hoanphungt the back-end features will be developed next sprint. 

![image.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/52bce4aa-4a74-4795-b48c-ec33aa684450)

**Comment by hoanphungt** [comment]
ooops that would be very nasty indeed. Maybe @LirryPinter can also come up with some idea on how to show them in the `details` tab of the selected monitoring network as it would be way too much to display in a table.

**Comment by LirryPinter** [comment]
@joeriverheijden @hoanphungt 

I agree that we need to have a solution for this. One question though.
Is this something we want to support, or did this come from the users? Are there already monitoring networks that have these amounts of observation types?

For the details tab we can have 2 solutions:
- We decide on a maximum amount of observation types shown and we make a new row under it with "And 399 more" or something similar.
- The whole details tab is scrollable, but this will remove white space which already isn't abundant in the catalogue.  If this is the chosen solution we really will need a custom scrollbar I think. Also this will increase loading times I guess. 

Let me know what you guys think!

**Comment by hoanphungt** [comment]
@LirryPinter 

For the details tab, I like the first solution that you had. It's just a representation of the full data anyway, so they can always select that timeseries to see all the observation types that it has later on. If there is 1000 observation types, I doubt anyone would want to scroll all the way to the end without a filter option.

@lexvand 
I cannot estimate this one yet until we have a design for it and decide on a final solution but let's say 1.5 story points.

**Comment by hoanphungt** [comment]
Hi @LirryPinter 

A design for the filter of observation types in timeseries selection modal is still missing. Could you have a look? Also, by default, how do we want to show a list of like 5000 observation types?

**Comment by LirryPinter** [comment]
@hoanphungt 

Design is updated (it is in the screen called 'updated: period is now filter'

- The period selection is now a filter
- Searchbox for observation type is added in the selection modal

**Comment by hoanphungt** [comment]
Hi @LirryPinter 

As discussed, we still need to come up with a way to handle a lot of observation types in the timeseries selection modal when we first open the modal.

I thought of a few options and share it here: 

For example, we have 500 observation types for the selected monitoring network. When first open the timeseries selection modal, we show:

1. Show 10 first observation types from the API and a text: `490 more`. Click on `490 more` will navigate to observation type sub-endpoint of this monitoring network. Users can use the search bar to search for their desired observation type.

2. As you suggested, a search box + dropdown. Show max 10 results in the dropdown. Type in search box and enter to filter. Select a result from the dropdown to apply the filter.

Option 1 will be very quick, option 2 would require some more work to make a custom dropdown. What do you think? @LirryPinter @joeriverheijden.

Also, could you please adjust the design when we have the final solution? @LirryPinter 

Kr, Hoan

**Comment by hoanphungt** [comment]
Discussed with Lirry. For the observation types filter in the timeseries selection modal, we would like to have a selection dropdown to allow users to search through a list of observation types, similar to this: https://semantic-ui.com/modules/dropdown.html (scroll down to search selection part). This selection dropdown can then be used for the management client as well.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom

Could you review this ticket? I don't really want to use the sematic-ui library for the selection dropdown of observation types so I chose a built-in one from html (`datalist`). It worked out quite well I think. Please let me know what you think.

Kr, Hoan

**Comment by Derryrover** [comment]
starting review

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan, 

Code looks good and works well.

The datalist html element looks like a wise decision. 
Good to not load in a lot of external libraries.

The change is certainly an improvement over the previous situation.
Ideally we might want to support selecting multiple observation types, but I suspect the backend does not yet support this in the api right?

You can merge

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Thanks for your review and yes, backend does not support multiple filters of observation types.
