### ISSUE TITLE
Mapbox - New acces token

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-catalogue#212]
Change to the new mapbox acces token.

See the example how it is done here:

https://github.com/nens/lizard-management-client/pull/458/files

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,
While working on the catalog could you also  change the mapbox acces token how it is doen here?:
https://github.com/nens/lizard-management-client/pull/458/files

Thanks in advance !

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
I changed it via this commit: https://github.com/nens/lizard-catalogue/commit/ec2a5769ddd26c8d36cc55fbb316ad4a53e82e2d
