### ISSUE TITLE
The map of locations crashed when there is only one location resulted from the search

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#215]
Map crashed when only 1 location resulted from the API call. This is because in this case, the bounds of the map cannot be identified. The map in this case should take the resulted location as its center point with a certain zoom level.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Would you have time to review the connected PR of this issue? 

The map crashed when only 1 location is found from the search. For testing, you can either search for: `Brink_Haarzuilens_DL_0051` or `Ridderhoflaan, Overstort`.

Kr, Hoan

**Comment by Derryrover** [comment]
Approved and ready to merge!
Tested and works, reviewed code looks good.
kr Tom

**Comment by hoanphungt** [comment]
Thanks Tom, I merged it
