### ISSUE TITLE
Go back to original map extent for location map

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#216]
In the map for locations of a monitoring network, when we zoom into a location, it would be nice to have the option to go back to the original map extent of the map.

**Comment by hoanphungt** [comment]
@LirryPinter 
Hey Lirry, what do you think about this? Sometimes when I click on a selected location to zoom in, it's very inconvenient to go back to the original view of the map (I have to zoom out many times to go back).

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

I added a button to zoom back to the original map extent of all locations visible on the map. There is no visual design for it. Would you like to review: https://github.com/nens/lizard-catalogue/pull/236? 

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Looks and works good!
ready to merge

kr Tom

**Comment by GeOdin** [comment]
Hey Hoan,

It looks good!
Approved. :)
