### ISSUE TITLE
Add period filter to time series catalogue + make sure that start & end are updated based on selected locations

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-catalogue#220]
EDIT: While working on this ticket. Also have a look at this bug: https://github.com/nens/lizard-catalogue/issues/231

Design: https://xd.adobe.com/view/2ca9bb91-e3f0-45c8-bc17-a0f15a4dfefc-79fa/screen/dfa6c937-94a2-46ee-b452-6392908e42b2
___________________________________________________________________________________________________

Next to a filter on observation type we would like to add a filter on period. Based on the defined period the locations on the map should appear or disappear when they have data within that period.

Based on the selected locations the start and end within step 3 should be updated according to:

- start = location with the earliest start date
- end= location with the last end date.
  That way we make sure that all data is exported er opened in the portal.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-catalogue/pull/234? This PR also fixes the bug in https://github.com/nens/lizard-catalogue/issues/231.

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 
Looks good ready to merge!

**Comment by GeOdin** [comment]
Nice that you now get feedback when the start time was after the end time. :)
When the start time is before the end time, the portal shows the same timespan.

I noticed 4 things. Let me know if that is as designed or whether it becomes part to this ticket or a next ticket.

#### 1.  start and end time not the same in catalogue and portal if start === end time

* When you select the same start and end time in the catalogue and press 'SHOW IN PORTAL', the start and end time are no longer the same. The screenshots below are for the same start and end time of '30/12/2020 00:00'.

![20201230-catalogue-staging-start-end-time-same-1.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/286a47e8-8e3d-4cc8-827f-53ef665047ee)
![20201230-catalogue-staging-start-end-time-same-2.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/84f0e8d0-c51f-4e37-90bc-cb0d46a767a7)

#### 2.  invalid date time possible (int/ float)

* Values that are not valid date time values are possible. You seem to be able to enter integers and floats in the date time box for start and end time. When entering strings in the start time, the 'Export timeseries' buttons becomes greyed out. However, when entering a date in the start time and a string in the end time, the 'Export timeseries' button does not become greyed out.

![20201230-catalogue-staging-start-end-time-same-3.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/ab6b2e49-f663-4c2a-8a25-e79fbe93b102)

#### 3.  size int matters for grey out timeseries button

* An integer or float that has 5 numbers (before the comma) do not grey out the export timeseries button.
* An integer or float that has more than 5 number (before the comma) do grey out the export timeseries button.

![20201230-catalogue-staging-start-end-time-same-6.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/47a771b0-2065-4786-910b-ed7d3dd4b0f2)
![20201230-catalogue-staging-start-end-time-same-7.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/9392c531-8908-47f7-8bf5-2aa530abf57e)

#### 4.  show error message and grey out buttons for consistency?

* When there is no start time, the export timeseries button is greyed out. I was wondering... Would it be more consistent to also grey out buttons if no start time is set or the start time is before the end time and the red error message is shown?

![20201230-catalogue-staging-start-end-time-same-4.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/5e19ddd9-7b51-460c-aa80-4184792a96ff)
![20201230-catalogue-staging-start-end-time-same-5.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/d30e5161-570c-4e9e-b29e-7623f8db7cce)

**Comment by GeOdin** [comment]
@Derryrover @hoanphungt 

Hey guys, I also found this.
Is this what is supposed to happen?

Kind regards,
Madeleine

#### 5.  Export timeseries also does not seem to work.

I am not sure if export timeseries worked previously.
I tried to export timeseries with the export timeseries for an asset that has values (checked this on the lizard staging client).
But there are no values when I download the timeseries via the catalogue (De Bilt 06260).

Example below:

![20201230-catalogue-staging-start-end-time-same-8.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/c0d9337e-210f-42d3-94d0-e3bce2763bf8)

**Comment by hoanphungt** [comment]
@GeOdin 
Regarding your bullet number 5, there is no values when you export the timeseries which is the correct behaviour. It happened because of your period filter. From 01/01/2019 to 31/01/2019, there is no timeseries with data during this period as you can also see in the map, there is no locations on the map. If you change the start date to 01/01/2016 for example, then you will see values in the spreadsheet.

**Comment by hoanphungt** [comment]
@GeOdin  
Hi Madeleine,

Thanks for your findings. I made this PR: https://github.com/nens/lizard-catalogue/pull/240 to address these issues and made another staging release to test the fixes. Regarding these issues, I addressed them as follows:

1. start and end time not the same in catalogue and the portal when start === end: 

This is because in the portal only the date is taken into account, not the time, so the time input doesn't matter but only the date. The format that I used to open the timeseries in the portal is `MMM,DD,YYYY-MMM,DD,YYYY`, so for example: `Jan,20,2020-Jan,21,2020`.
@lexvand Do you think this is sufficient?

2. Invalid date/time input (integer/float/characters):

In the PR, I made a quick fix for it so they become invalid in this case (but not when you enter an integer with less than 6 number). I used moment library and for integer with less than 6 number, it can be translated to a date value. 

3. size int matters for grey out timeseries button: as mentioned earlier, the moment library can translate integer with less than 6 number to a date value

4. Consistency in error feedback:

I improved the error feedback and disabled button by:
- Disabled timeseries export button when there is error feedback with help text when hover over the button (i.e. invalid date inputs, start date is after end date, no location/timeseries is selected)
- Disabled timeseries export button when no start date is provided with help text when hover over the button (help text = Please enter a start date to export timeseries). The reason that I don't provide an error message here is because sometimes, you don't want to use the period filter to export timeseries but only to view the timeseries. In this case, no need to enter a start date. 

5. As I explained in the previous comment, it is not a bug but happened due to your period filter.

Could you have a look again on staging to see if the fixes are good enough?

Kind regards
Hoan

**Comment by GeOdin** [comment]
@hoanphungt 

Hey Hoan :)

Thank you for your improvements.
It looks good!

Kind regards,
Madeleine

**Comment by lexvand** [comment]
I'm afraid the filter can't work correctly based on only AND filtering in the API. I made a drawing to illustrate the issue.
![image](https://user-images.githubusercontent.com/5370809/106160863-951ab700-6186-11eb-802b-66f8aede9b0d.png)

These 4 periods should result in a match with the given timeseries object. Currently we only support number 4, which is quite an unlikely use case. The logic would require an OR statement to make different combinations of correct filters comparing ts__start with filter_start and filter_end and comparing ts__end with filter_start and filter_end.

We need another filter in the API to support this feature, which does an intersect. It requires more logic in the backend. A quick fix to make it more useful in the meantime is to flip the signs, meaning:
`timeseries__start__lte=2019-01-01T00:00:00Z&timeseries__end__gte=2021-01-27T00:00:00Z` instead of `timeseries__start__gte=2019-01-01T00:00:00Z&timeseries__end__lt=2021-01-27T00:00:00Z`

@hoanphungt Could you fix that?

**Comment by lexvand** [comment]
@hoanphungt Discussed with Tom en he had experience with this type of queries and it is possible to do it this way. It should become:
`timeseries__start__lte=2019-01-01T00:00:00Z&timeseries__end__gte=2021-01-27T00:00:00Z` instead of `timeseries__start__lte=2021-01-27T00:00:00Z&timeseries__end__gte=2019-01-01T00:00:00Z`

**Comment by hoanphungt** [comment]
@lexvand @Derryrover 
There will be 2 cases though:

1. Only start date is filled in: for example: `timeseries__start__gte=2019-01-01T00:00:00Z`. Should I also flip the sign in this case using the current moment as start?

2. Both start date and end date are filled in: is it correct that I would always flip the sign in this case to ensure all the 4 cases are covered? Then the query would become:

`timeseries__start__lt=2021-01-27T00:00:00Z&timeseries__end__gte=2019-01-01T00:00:00Z`

Btw, I can't figure what `lt` and `gte` in this case mean and why did you change the position of `lt` and `gte` in the above query? :)

**Comment by GeOdin** [comment]
@hoanphungt 

Hey Hoan :)

Could it be that lt stands for where the value of the field is less than (i.e. <) the specified value?
https://docs.mongodb.com/manual/reference/operator/query/lt/

Could it be that gte stands for where the value of the field is greater than or equal to (i.e. >=) a specified value (e.g. value.)?
https://docs.mongodb.com/manual/reference/operator/query/gte/

Kind regards,
Madeleine

**Comment by hoanphungt** [comment]
@GeOdin 
Ah nice! Yes, it seems the correct explanation of those terms. Also, `lte` means `less than or equal to` as well. 

In this case, I think my 2nd question is already answered. Only my 1st question left whether I should also flip the sign if only start date is filled in using the current moment.

**Comment by hoanphungt** [comment]
@lexvand 
Seems like for case number 1, only start date is filled in, if I flip the sign and use the current moment as start date like this query:

https://nxt3.staging.lizard.net/api/v4/monitoringnetworks/c6ef3248-e8c2-47b4-9c03-afe90d6ac9be/locations/?page_size=10000&timeseries__start__lte=2021-01-29T11:25:45Z&timeseries__end__gte=2018-07-01T00:00:00Z

It would return more results than the old query:

https://nxt3.staging.lizard.net/api/v4/monitoringnetworks/c6ef3248-e8c2-47b4-9c03-afe90d6ac9be/locations/?page_size=10000&timeseries__start__gte=2018-07-01T00:00:00Z

So I will also flip the sign in this case. One more question, the time passed in the query here should also be converted to UTC time, is it correct? Currently, it added the local time to the query. I am going to convert it to UTC before adding it to the query.

**Comment by lexvand** [comment]
@hoanphungt
Case 1: If only start is filled in the query becomes: timeseries__end__gte={filled in start}. 
Case 2: If only end is filled in the query becomes: timeseries__start__lte={filled in end}. 
Case 3: If both are filled in the query becomes: timeseries__start__lte={filled in end}&timeseries__end__gte={filled in start}. 

May sound counterintuitive, but the logic is correct.

**Comment by hoanphungt** [comment]
Ok, sounds good!

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom

Could you review this PR: https://github.com/nens/lizard-catalogue/issues/251? 

Steps to test:

- Select time-series in the lizard catalogue
- Select KNMI All monitoring network
- Open the Time-Series selection modal
- Select filters for the locations for 3 cases:

1. Only start date = 01/07/2018, no end date
2. Only end date = 01/01/2021, no start date
3. Enter both start and end dates: from 01/07/2018 to 01/01/2021

Kr, Hoan

**Comment by Derryrover** [comment]
Looks good you can merge !

**Comment by lexvand** [comment]
@hoanphungt Not yet on staging, right? Moved it to this new pipeline (see description for purpose of pipeline).
