### ISSUE TITLE
Improve selection dropdown for observation types in timeseries selection modal

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#226]
Currently, when you open the list of observation types and select one, the list will then only show the selected one, not the full list. This is not very intuitive for users.

**Comment by hoanphungt** [comment]
@lexvand 
Hi Lex, should I also pick this up during this sprint or after the raster form? The raster form is probably not gonna be finished during this sprint.

**Comment by lexvand** [comment]
@hoanphungt Yes, please do so. Good to wrap this up. Raster management is going to take a few more sprints.

**Comment by hoanphungt** [comment]
@joeriverheijden 
Hi Joeri, I improved the search dropdown for observation types in timeseries selection modal a little bit (to show the full list again when you open the dropdown after selection). Could you check on staging if this is an accepted behaviour for the dropdown? https://nxt3.staging.lizard.net/catalogue/?data=Timeseries

**Comment by hoanphungt** [comment]
Joeri checked and agreed with the solution. Deployed to staging and production.
