### ISSUE TITLE
Enable GetCapabilities URL for temporal rasters

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-catalogue#230]
This is now supported by the backend by adding time dimension information to the GetCapabilities page according to the OGC standard.

**Comment by hoanphungt** [comment]
@lexvand 
Hi Lex,

For temporal raster like Regen (https://nxt3.staging.lizard.net/api/v4/rasters/ad5bfe0f-6286-4576-8eaa-fbcf21d5ee82/), is https://nxt3.staging.lizard.net/wms/raster_ad5bfe0f-6286-4576-8eaa-fbcf21d5ee82/?request=GetCapabilities the correct getCapabilities url for it?

**Comment by lexvand** [comment]
@hoanphungt That looks quite right, right? Just like for the other rasters.

**Comment by GeOdin** [comment]
@hoanphungt 

Hey Hoan :)

I checked the GetCapabilities on staging and they seem to work.
For example Tuinders DIG (f4c528c6-7a02-4637-8bd1-c9f761edf03d) and Rice field flooded q0007_s (c000836a-2797-4ad5-bfe9-5356360b21dc).

According to the OGC standard for GetCapabilities requests, I think also 'service=wms' and 'version=<I am not sure which version it is>' should be added (https://docs.geoserver.org/stable/en/user/services/wms/reference.html#getcapabilities). The GetCapabilities request from the catalogue work, but they might cause other issues if we do not use the other parameters.

@lexvand 
Which version do we use?

Kind regards,
Madeleine

**Comment by hoanphungt** [comment]
@lexvand 
Hi Lex, do you know which version I should add to the URL for the GetCapabilities request?

I see in the XML response the version is 1.3.0 which is also the latest version. So probably this one would work.

**Comment by lexvand** [comment]
We only support version 1.3.0 for GetCapabilities (and it is in the response) and it is also by default the WMS service. I see no need to include these parameters in the URL. 

The documentation that is referred to is from Geoserver, not of the OGC standard. Geoserver generally supports 2 versions, so that's why they consider it required.
