### ISSUE TITLE
Change ORGANISATION in ORGANISATION (OWNER) 

### ISSUE THREAD

**Issue by lisannewapstra** [nens/lizard-catalogue#241]
Topdesk 2006 0058 Shared with organisation - Catalogus by Jelmer (also mentioned by others) 

The term or filter "organisation" appears to be confusing. Users expect to also see the "shared with" data there.
Therefore, Joeri and I propose to change

ORGANISATION into ORGANISATION (OWNER) 

![image.png](https://images.zenhubusercontent.com/5ef5e8f83e5d5435204918ce/bd613f11-56c4-46c5-8528-ddc8af236661)
@joeriverheijden 
At both the 1 and the 2 position?

**Comment by hoanphungt** [comment]
Hi @lisannewapstra,
Do we want to change `ORGANISATION` into `ORGANISATION (OWNER)` at both places 1 and 2 in your photo or only at place 1?

**Comment by lisannewapstra** [comment]
I prefer both, but 1 would also be helpful if 2 is difficult to change.
