### ISSUE TITLE
Use snackbar notification when exporting timeseries in timeseries selection modal

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#243]
Currently, when exporting timeseries using the timeseries selection modal, there is no visual feedback to users whether the export has started or failed to start. I (Hoan) discussed this issue with Lirry and we both agreed to use the notification bar (snackbar) in the management client for this type of notification.

Snackbar design from management client: https://xd.adobe.com/view/80bc79b4-fbd2-4d42-9d7f-00b84d2e89c3-d5ef/screen/7ed4a8c0-7e06-412a-bf78-37d73a6e14a5

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-catalogue/issues/247? I implemented it in the same way with the notification in management client.

Kr, Hoan

**Comment by Derryrover** [comment]
Good !
ready to merge
