### ISSUE TITLE
Filter period in timeseries selection doesn't cover use cases

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-catalogue#249]
See: https://github.com/nens/lizard-catalogue/issues/220#issuecomment-769171512

Additionally, I think it's wrong to use this start and end for both filtering locations and for the export period, especially when we let the datetime entries respond to the selected timeseries (which according to the title was a requirement in #220, but fortunately seems not yet implemented). 

To make the filter work we need a special intersect filter. This should be discussed with backend, as it may not be very straightforward to add.

Also we need to have a critical look at the workflow, what use cases we want to support and what that means for possible improvements in the interface. See also #250.

**Comment by lexvand** [comment]
@joeriverheijden @LirryPinter Some unintended behavior we really need to have a look at. It makes quite an unprofessional impression if we release this, I'm afraid.

**Comment by joeriverheijden** [comment]
Let's discuss this today Lex. I think i don't really get the point while reading the comments..

**Comment by lexvand** [comment]
Was fixed by adjusting the filter.
