### ISSUE TITLE
When filtering on an observation_type you get all timeseries of a selected location

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-catalogue#250]
It is not intuitive that when you filter locations on a specific observation_type, select a location and make an export, you export all available timeseries of that location. Even the ones that have a different observation_type than you filtered on. This is very messy.

Instead of locations (and with that all related timeseries) you would like to select the separate timeseries. Can we change this in the **TIMESERIES** modal?

**Comment by hoanphungt** [comment]
@lexvand 
Hi Lex,

Just want to check with you the work-flow for this timeseries export modal:

1. Users selects a location(s) on the map using several filters: the search bar, the observation type filter and the period filter
2. Users see a list of timeseries which belong to the selected locations on the right side. Here they can remove unwanted timeseries.
3. They now can choose whether to: 
- Export the selected timeseries (using the export modal) OR
- Go back to step 1 to select more timeseries using the same method

Is it correct?

**Comment by lexvand** [comment]
@hoanphungt That's correct. With the addition that in step 1 in case the observation type filtering is active the user only selects those specific timeseries of the locations that are being selected. In case of no observation type filtering all related timeseries are added to the list.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you also review this PR: https://github.com/nens/lizard-catalogue/pull/256/? I think this is a good improvement for the work flow of the timeseries export task. I'd like to hear your opinion.

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,
Looks good
ready to merge
kr Tom
