### ISSUE TITLE
Improve export timeseries workflow (experienced as a bug)

### ISSUE THREAD

**Issue by lisannewapstra** [nens/lizard-catalogue#254]
Via Joeri

> ### Original Topdesk Ticket Joeri - 2102 0163 Fwd: inloggen in validatietool meetreeksbeheer
> ![image](https://user-images.githubusercontent.com/33685743/108538717-630cf880-72df-11eb-837a-004948add0d4.png)
> 
> Hi,
> De exportknop in de catalogus licht niet groen op als je bent ingelogd en is daarmee niet beschikbaar voor de gebruiker. Ik denk dat dit verband houdt met die nieuwe manier van inloggen.
> Mag met hoge prio opgepakt worden door het team.
> 

### Analysis Support
I do not think it has to do with being logged in. And it also works with rasters.
For timeseries, there seems to be a Start time required.

With Start
![image](https://user-images.githubusercontent.com/33685743/108539324-242b7280-72e0-11eb-86ba-8795e69e8646.png)

Without start
![image](https://user-images.githubusercontent.com/33685743/108539355-2e4d7100-72e0-11eb-8195-fd95987ac6cb.png)

Is this by design?

**Comment by lexvand** [comment]
What needs to be done to make this work for users:
- The start and end fields in the timeseries modal only apply to the filtering of locations on the map
- Only grey out the export button if no timeseries have been selected
- When clicking "Export" open a new modal in which the user can define the export period (start to end) and click a "Start export" button or cancel
    - If start and/or end are filled in in the main modal, inherit these values as default for the export period modal

**Comment by lexvand** [comment]
@LirryPinter Can you adjust the design with this second modal?

**Comment by LirryPinter** [comment]
Modal with:

- Message
- Start + end point (if there has been filltering, take that one as default)
- Cancel and export button

**Comment by LirryPinter** [comment]
Design is updated.

Added a modal for selection the period for the export!

@lexvand @hoanphungt

**Comment by hoanphungt** [comment]
Design link: https://xd.adobe.com/view/2ca9bb91-e3f0-45c8-bc17-a0f15a4dfefc-79fa/screen/3cee670d-a5b2-4ef4-a6dd-1392c3a41ea3/specs/

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-catalogue/pull/255/? Design link is in the above comment.

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Overall looks and works good.
Ready to merge

2 notes:

- Small question in the pr regarding ts.config (could be fixed later)
- Not sure what to do, butI think the already not so clear workflow for the user is improved, but in a way it also got worse. Yet another modal, falling on top of details the user might still be interested in. Also 2 modals to close now before user can actually click to the results of the export.

kr Tom

**Comment by hoanphungt** [comment]
@lexvand @joeriverheijden 
Hi Joeri and Lex,

I think Tom's above comment makes sense here. Adding another modal on top of the timeseries selection modal seems to be quite cumbersome since it hides some of the information in the other modal. However, since I already made it, I think it would be best if I put it on staging and let you two and @LirryPinter experiment with this to see the pros and cons compared to the previous exporting method.

Kr, Hoan
