### ISSUE TITLE
Refactor MainApp, Header and FilterBar components to hooks components

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#258]

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

I think this is a very good initiative!
Liked how you refactored this.

I approved, because i see no code problems and also no bugs.
But I find it hard to oversee all the details.

Maybe we must advice some more intense testing before going to prod?
How do you think?

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Yes I agree.

@lexvand 
Hi Lex, it would be nice if you can perform some intensive tests for this change. Mostly about if data is still loaded correctly (e.g. observation types, organisations, rasters, wms layers, monitoring networks, locations, timeseries) and if the URL is updated correctly with the filter selections.

**Comment by lexvand** [comment]
Can't find any problems related to this while testing.
