### ISSUE TITLE
Reset list page to 1 when filter options are updated

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-catalogue#261]
Actions:
- Go to catalogue, e.g. WMS layers
- Go to page 2 of the listed items
- Update the filter (e.g. dataset) which results in less than 2 pages
- API responds with 404 as page 2 of results does not exist

Page number should be reset to 1 when filtering is updated. Otherwise it keeps loading.

**Comment by hoanphungt** [comment]
@lexvand 
I find this issue quite annoying and this bug also happens when you use the search bar. This is because of my last attempt to refactor the catalogue using react hooks. Nice that you found it out. So I fixed it.

**Comment by lexvand** [comment]
Fix works.

**Comment by lexvand** [comment]
@hoanphungt No other issues for the catalogue on the board, so this one can be released to production.

**Comment by hoanphungt** [comment]
Deployed to production 0.2.24
