### ISSUE TITLE
Hard to reset observation type filter in timeseries selection modal

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-catalogue#263]
I had to click a lot to find out how to clear the observation type filter in the timeseries selection modal. You can only do it by selecting (another) one, as in that case the cursor is in the field and you are able to delete the search entry.

Probably not a quick fix in the existing field. Maybe refactor it based on management client field...?

**Comment by hoanphungt** [comment]
@lexvand 
I think this one can be fixed by using the same dropdown from the management-client and it would greatly improve the user experience with the timeseries modal. 

Since my sprint is still quite empty, would it be a good idea for me to pick it up this sprint? I estimate it can take 1 point.

**Comment by lexvand** [comment]
@hoanphungt That's a good one. But first please pick up the issues in the management client.

**Comment by lexvand** [comment]
Tested on staging. Works much better now.

**Comment by hoanphungt** [comment]
on production
