### ISSUE TITLE
Add version number within the webapp (see epic for example)

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-catalogue#265]

**Comment by Derryrover** [comment]
@lexvand 

Hi Lex,
I added this to the next sprint.
I think a small effort for lots of increased convenience
kr Tom

**Comment by Derryrover** [comment]
merged without review.
https://github.com/nens/lizard-catalogue/pull/267
deployed to staging 0.2.24
https://nxt3.staging.lizard.net/catalogue/?data=Raster

**Comment by hoanphungt** [comment]
Deployed to production 0.2.24
