### ISSUE TITLE
Manage icon broken and user roles on staging not working

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#273]
Reported by Joeri:

- Manage icon (to go the management page) is broken
- On staging, the manage icon is not visible due to the way to achieve user role has been changed after the last staging release

**Comment by lexvand** [comment]
Fixes work. It looks like it has already been released to production. Correct, @hoanphungt?

**Comment by hoanphungt** [comment]
@lexvand 
Only part 1 has been released to production to fix the broken icon. The 2nd part to fix the user roles in organisations needs to wait for the backend release before going to production.
