### ISSUE TITLE
Check links to Lizard viewer and adjust to correct url when introducing the landing page

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-catalogue#278]
On staging the "Open in portal" button leads to a portal configuration that doesn't include a correct background map. Relates to nens/lizard-nxt#5012.

**Comment by Derryrover** [comment]
PR:
https://github.com/nens/lizard-catalogue/pull/289

Some links to portal and management were broken.

Not sure what is ment in the description with """" On staging the "Open in portal" button leads to a portal configuration that doesn't include a correct background map."""

Will ask Lex

**Comment by Derryrover** [comment]
@lexvand 

Hi Lex,

I did fix some problems with the url in the pr, but could not reproduce the following you describe:

>>""
On staging the "Open in portal" button leads to a portal configuration that doesn't include a correct background map.
""

Could you add the urls that you encounter?

kr Tom

**Comment by Derryrover** [comment]
merged withour review.
On staging ap part of 0.2.31-0

**Comment by lexvand** [comment]
The generated link in the basket isn't correct. It contains `/catalogue`. The link for a single object in the right side bar does work now.

@Derryrover Can you also change all references to **portal** into **viewer**?

**Comment by lexvand** [comment]
@Derryrover And please remove the hyphen here:
![image](https://user-images.githubusercontent.com/5370809/128479361-b99ebe77-32d7-4710-a1e6-4895ce9a4d1d.png)
