### ISSUE TITLE
Remove large page_size query in API calls

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#280]
Similar to the lizard-management-client, it would be good to remove large page_size queries (page_size=0 or page_size > 1000).

Especially, the one in the timeseries selection modal really has performance issue and sometimes leads to 504 - Gateway Timeout as found in here: https://github.com/nens/lizard-catalogue/issues/246.

Places where changes have been made:

- `/api/v4/organisations/?page_size=0` --> to page size 1000
- `/api/v4/{userId}/organisations/?page_size=0` --> no page size query
- `/api/v4/observationtypes/?page_size=0` --> to page size 10000
- `/api/v4/datasets/?page_size=0` --> to no page size query
- `/api/v3/inbox/?page_size=100000` --> to no page size query
- `/api/v4/rasters/${rasterUuid}/projections/?page_size=100000` --> to page size 100

Monitoring network endpoint:
- `/api/v4/monitoringnetworks/${uuid}/timeseries/?page_size=10000` --> to page size 100 **(important)**
- `/api/v4/monitoringnetworks/${uuid}/observationtypes/?page_size=10000` --> no change
- `/api/v4/monitoringnetworks/${uuid}/locations/?page_size=10000` --> to page size 1000
- `/api/v4/monitoringnetworks/${uuid}/locations/?page_size=10000` --> to page size 100

**Comment by hoanphungt** [comment]
@lexvand 
While working on the issue with large page_size in the lizard management client, I think it would be good to also implement the solution there to the lizard catalogue. Then hopefully we can solve some of the performance issue especially with the timeseries selection modal.

I want to pick this issue up during this sprint. What do you think?

**Comment by lexvand** [comment]
@hoanphungt Yes, please do so. Can you add an estimate?

**Comment by hoanphungt** [comment]
@Derryrover 
Could you review this PR: https://github.com/nens/lizard-catalogue/issues/281? 

I am not done yet as there are still certain things I want to address but I think it's good for you to review it now. 

My main concern now is that for the large response. for example when you go to the Timeseries Selection modal of the `N&S large sample` monitoring network, it is gonna load more than 5000 timeseries so instead of sending 1 request with `page_size=10000`, it is now sending > 50 requests with `page_size=100`. In this case, I am not sure which one is better anymore. I asked Carsten and he also thought 50 requests are a lot and maybe we need to find a common ground between page size 100 and page size 10000.

Another concern of mine is that the above 50 requests will be sent to the server until it is completely finished, no matter if at that time, I closed the modal as maybe I don't want to wait anymore and would like to check out other things. I think this is unnecessary but couldn't find an easy way to stop it yet. What do you think about this issue?

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

I am thinking to refactor this to use react-query as discussed with Remco last meeting. Still, I would like to hear your opinion about the matters that I stated in the previous comment:

> My main concern now is that for the large response. for example when you go to the Timeseries Selection modal of the N&S large sample monitoring network, it is gonna load more than 5000 timeseries so instead of sending 1 request with page_size=10000, it is now sending > 50 requests with page_size=100. In this case, I am not sure which one is better anymore. I asked Carsten and he also thought 50 requests are a lot and maybe we need to find a common ground between page size 100 and page size 10000.
> 
> Another concern of mine is that the above 50 requests will be sent to the server until it is completely finished, no matter if at that time, I closed the modal as maybe I don't want to wait anymore and would like to check out other things. I think this is unnecessary but couldn't find an easy way to stop it yet. What do you think about this issue?

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan
Yes excellent that you investigate react query

>>it is gonna load more than 5000 timeseries so instead of sending 1 request with page_size=10000, it is now sending > 50 requests with page_size=100. In this case, I am not sure which one is better anymore.

I cannot tell you which one is better, we (or backend) could maybe run a test to determine that.
I also think this problem has to simple solution right now and may require some backend work.
Worth to consider:
- 1 request with 5000 records only need one round trip over the internet. while 50 seperate request need 50 round trips over the internet. 
- the backend now sends back all the data for those records, but we are only using the lat long (+ maybe label). The backend could support that we provide a list of required fields. This will make the size of the response smaller.
- we will soon investigate vector tiles. I am not sure yet but I think vector tiles solve this by showing fewer assets when zoomed out and more when zoomed in. Regardless if we are going to use vector tiles yes or no, we could think about how we could use similar strategies to solve this problem.

>>Another concern of mine is that the above 50 requests will be sent to the server until it is completely finished,

The paginated requests will be send in series (not parallel). At each given time only one request is underway/busy. You might investigate if there is a way to stop the upcoming requests from being send if the user closes the modal. How to do this depends on the technology used (hooks vs recursive vs redux). I am not sure how to do it with hooks. Maybe you could investigate it further and show Remco and me what you found. I am also interested how react query will work together with paginated fetch. Are they compatible?

kr Tom

**Comment by hoanphungt** [comment]
Investigating to use react-query instead of the usePaginatedFetch custom hook

**Comment by hoanphungt** [comment]
Solve some of the large queries using page_size=0 or page_size=100000 in the catalogue. For example:

- `/api/v4/inbox/`
- `/api/v4/organisations/`
- `/api/v4/{userId}/organisations/`

Also use a function called paginatedFetch to make the page_size smaller and to build the whole records of the object based on the `next` parameter. 

The page_size queries are adjusted to a reasonable number in multiple places but not to be completely removed as in some cases, it's better to send 1 request with large page_size query than > 50 requests with small page_size query.

This is already a good improvement for the catalogue as the issue of sometimes a very large page_size query cannot be resolved is not happening anymore.

**Comment by hoanphungt** [comment]
@Derryrover 
Thanks for your comment. I made several tickets based on your comment.

**Comment by lexvand** [comment]
I tested the changes and for those endpoints that require multiple requests it works good. The ones that cannot be tested because of lack of paginated results are expected to also work properly, like we've seen in the management client. Nice work!
