### ISSUE TITLE
Investigate on the use of react-query instead of Redux store

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#284]
Currently in the catalogue, backend data is mostly stored in the Redux store, for example:

- observation types
- organisations
- datasets
- monitoring network locations
- monitoring network observation types
- monitoring network timeseries
...

We can investigate if using react-query will remove some of them from the Redux store and if they can prove to be more efficient than Redux.

**Approach:**

The approach is to gradually move to react-query in a careful way (from simple places first) and then analyse the impact of this move before making a decision for which technology to use (Redux vs react-query).

**Comment by hoanphungt** [comment]
Spent 1 day to add react-query to the catalogue and refactor the paginatedFetchFunction to use the recursiveFetchFunction in multiple places

**Comment by lexvand** [comment]
@hoanphungt Why is this issue in the backlog? Is it partly done and should the rest be picked up later?

**Comment by hoanphungt** [comment]
Many parts of the Redux store cannot be replaced by React-Query (mostly the filter options) as these informations are shared between many different components. React-Query is best to store API data but in this case, it is more appropriate to store these filter selections in a global state (Redux in this case). 

Some other parts that concern data fetching only have already been done with React-Query, e.g. paginated fetches, scenario results.

So I close this ticket as completed.
