### ISSUE TITLE
Export rasters - configure what value the "no data" value has.

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-catalogue#287]
When exporting raster tiffs the backend now supports that you can choose the value of your "no-data" value.
https://github.com/nens/lizard-nxt/issues/3621

In the catalog you should also be able to choose the value of your "no-data" value.

**For example**

If the user chooses as "no data value" the value "-9999" (often used for 3di), then all empty values in the raster will have the value -9999.

**Comment by Derryrover** [comment]
@lexvand 
@joeriverheijden 

FYI: I made this ticket.
Please move to the correct sprint, release and epic.

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,
Looks good.
I think it is a bit hard to make this into something perfect, but I think this solution is good enough.
kr Tom

**Comment by lexvand** [comment]
Tested on staging. It all works:
- Default nodata by leaving field empty
- Float nodata for float data
- Integer nodata for integer data
- Error for incorrect nodata type
