### ISSUE TITLE
[CANNOT_REPRODUCE] catalogue loads from cache - even after CTRL+SHIFT+R

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-catalogue#290]
Unclear since when or why this problem happens.
Is it because of nginx?
It seems to be a new problem, because I have not heard it mentioned yet on prod.
We have similar problems more often but always CTRL+SHIFT+R resolved this.
But now it does not.
Problem seems to happen only in Chrome (not sure).
It may have something to do the following: When we open catalogue, we straight away get redirected to page with query parameter.  When we do a CTRL+SHIFT+R this actually refreshes the cache for the page url including the query parameter, but for the site without the query parameter it will still load from cache.

**Steps to reproduce**
Open chrome browser
Go to nxt3.staging.lizard.net/catalogue
Hover over the header icon to see v0.2.30
Now do CTRL+SHIFT+R
Hover over the header icon to see v 0.2.31-0
No go in the url bar to nxt3.staging.lizard.net/catalogue again (remove the url query) and hit enter.
The page reloads. 
Hover over the header icon again and the app is ..... v0.2.30

**Workaround**
You can clear cached images and files in chrome as described here:
https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DDesktop
Only delete cached images and files, nothing else needs to be deleted!

**Comment by Derryrover** [comment]
@lexvand 
@joeriverheijden 

Hi Lex and Joeri,

Found this bug. Not sure if it is easily solvable.
Should I spend time on it?
If not then each user may have to perform the workaround.

This also means you both have to perform this workaround before testing !

kr Tom

**Comment by lexvand** [comment]
This doesn't occur for me, both on Chrome and Firefox. I'm on 0.2.31-1 and stays that way after hard refresh. 

Difficult to assess how this influences the use by our users. As long as we do not have better information I think we should leave it be. We could let Ronald have a look next Tuesday...
