### ISSUE TITLE
Scenario Table

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#300]
ToDo:

- [x] Search bar: filter by name, model_name and UUID
- [x] Table with following columns: name, model_name, username, organisation, access modifier, last_modified
- [x] Ordering on all columns: name, model_name, username, organisation, last_modified
- [x] Pagination
- [x] Add to basket feature

**Comment by hoanphungt** [comment]
@lexvand 
There are 2 things I want to ask you here:

- Do we want to also add a date column to the table based on `created_date` or `modified_date` of the scenario? we then can also sort the list based on this date field.
- Do we want to have the `Add to Basket` feature for the scenario so then we can open the basket and open all the selections in the Lizard Viewer at once?
- I only just found out that we cannot sort the scenario list using the `organisation__name` yet. I missed it yesterday: https://nxt3.staging.lizard.net/api/v4/scenarios/?page=1&ordering=organisation__name. I will make a ticket for it.

**Comment by lexvand** [comment]
- Yes, last_modified is most useful
- Yes, especially useful to add multiple scenarios to compare model results
- Will see if Remie can also include organisation__name filtering in the next release

**Comment by lexvand** [comment]
Will be taken care off in nens/lizard-nxt#5385.

**Comment by lexvand** [comment]
Tested on staging. It all works just fine.
