### ISSUE TITLE
Scenario Details

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#301]
ToDo:

- [x] Main infos: name, organisation, model_name
- [x] Map preview: based on the raster result's bbox if available --> not included anymore to save space for the scenario results
- [x] WMS GetCapabilities link: e.g. https://nxt3.staging.lizard.net/wms/scenario_5483fadd-6608-4134-bc6c-fc6039415358/?request=GetCapabilities
- [x] Details tab: metadata of scenario
- [x] Action tab: open in viewer, open in API
- [x] Scenario results action(s) --> https://github.com/nens/lizard-catalogue/issues/302

**Comment by hoanphungt** [comment]
@lexvand 
For the details view, I have 2 questions:
1. How to retrieve the raster result of a scenario to get the bbox and preview it on the map?
2. How to open the scenario in the Viewer?

**Comment by hoanphungt** [comment]
@lexvand 
For the details view, I have 2 questions:
1. How to retrieve the raster result to get the bbox and preview it on the map?
2. How to open the scenario in the Viewer?

**Comment by lexvand** [comment]
1. A scenario has a results subendpoint. Have a look at the management client, where the results are listed in the form.
2. Example link: https://demo.lizard.net/viewer/nl/map/topography,scenario$86a043c/point/@52.1858,5.2677,8/-2Days0Hours+0Days3Hours

**Comment by lexvand** [comment]
Test on staging. @hoanphungt Two small improvements:
- Spelling: Change "Lastest update" to "Last update"
- Remove line "For ICMS", that's no longer relevant and will be removed from the data model soon (I should have specified that in the Epic)

**Comment by hoanphungt** [comment]
Ah ok. Together with the above 2 small fixes, I also made some other improvements to the styling of the Details panel:

- The scrollbar now moves from the whole details panel to inside the Details/Actions/Results box when the content overflows. The box also not jumping in height anymore when moving between tabs (when content overflows in some of the tabs). For example: https://nxt3.staging.lizard.net/catalogue/?data=Raster&uuid=ad5bfe0f-6286-4576-8eaa-fbcf21d5ee82 and https://nxt3.staging.lizard.net/catalogue/?data=Scenario&uuid=9c35ad08-c83d-43fd-88ac-a7d49625aa85
- Refactor to use css module
- New action tab
