### ISSUE TITLE
Scenario results

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#302]
ToDo:

- [x] Design for scenario results view: https://www.figma.com/file/a242LIsJnGvE6diV3CgGjF/Wireframe---Scenarios-in-Catalog?node-id=8%3A35
- [x] Results tab
- [x] List of scenario results
- [x] Link to raster export modal for raster results
- [x] Download for non-raster results
- [x] Stylings

Example in the management client: https://nxt3.staging.lizard.net/management/data_management/scenarios/9c35ad08-c83d-43fd-88ac-a7d49625aa85

**Comment by lexvand** [comment]
Staging test: Looks and works good.
