### ISSUE TITLE
Refactor action buttons in the action tabs following new design

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#305]
Follow the design by Gijs:

https://www.figma.com/file/a242LIsJnGvE6diV3CgGjF/Wireframe---Scenarios-in-Catalog?node-id=8%3A142

Also refactor the styling of the Details panel.

**Comment by lexvand** [comment]
@hoanphungt Looks fancy!

Just a couple of small textual improvements:
- Remove "selected" from Timeseries action description (already used twice in different forms)
- Remove "playback and" from Raster and WMS layer Open in Viewer action description (is more specific for scenarios, not really applicable to these data types)

**Comment by hoanphungt** [comment]
@lexvand 
Deployed to staging again. When do we expect to make a production release for this scenario epic?

**Comment by lexvand** [comment]
@hoanphungt We want to prepare a release mail towards our customers, including Geoblocks mangement. For that I first want to make some improvements in the documentation. I expect we can release to production at the beginning of next week.
