### ISSUE TITLE
Adapt to changes in Scenarios data model

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-catalogue#314]
See results of: nens/lizard-nxt#5443 and nens/lizard-nxt#5442 and [description](https://github.com/nens/lizard-nxt/issues/5416#issuecomment-1087330846) of backend changes

- [x] Adjust to changes in data model
  - [x] Drop username field in table
  - [x] Apply name changes for existing attributes in Details tab
  - [x] Change filtering/ordering where needed
  - [x] Show extra_metadata content to Details tab (need to discuss how to handle multiple levels in JSON dict; in first place only first order attributes): created its own ticket: https://github.com/nens/lizard-catalogue/issues/317
- [x] Add filtering on Project in left sidebar.

**Comment by hoanphungt** [comment]
@lexvand 
For the extra_metadata, I created a ticket for this issue as I don't know yet how to best display this information in the Details tab of the catalogue: https://github.com/nens/lizard-catalogue/issues/317
