### ISSUE TITLE
Show extra_metadata field in Details tab of the Scenario catalogue

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#317]
The new extra_metadata field in the scenario endpoint is an object. How can we best display this field in the scenario details tab?

**Comment by hoanphungt** [comment]
@gijs @lexvand 
Do you guys have any suggestion on how we should display the `extra_metadata` field of a scenario in the Details tab?

**Comment by lexvand** [comment]
@hoanphungt 
I think the easiest way would be to just add it to the details tab. Maybe add a header below the default rows if any extra_metadata is available and add all attributes as additional rows. We need to make it scrollable then.

Some edge cases we probably need to handle:
- If there is more than one level in the JSON: Can we flatten them by concatenating the attribute names?
- If there are arrays of attribute values in the JSON: Tricky one. Maybe best handle them as one object?
- Anything else?

An alternative would be to open the extra_metadata in a separate modal, but that is less elegant and less user friendly.

**Comment by hoanphungt** [comment]
@gijs 
Hi Gijs,

For the extra_metadata field of a scenario in the Details tab of the Catalogue, I struggle to display them in an useful way. The field is an object. I made an attempt like this:

![Screenshot from 2022-04-26 11-29-38](https://user-images.githubusercontent.com/43402556/165269807-717a5d47-df1b-4651-afa9-09d3cba15441.png)

As you can see, the object field contains another object so it can become messy here and also does not fit into the table anymore (although you can hover on it to see the value).

What do you think about this solution and do you have any other suggestion?

**Comment by hoanphungt** [comment]
@lexvand I just deployed to staging

**Comment by lexvand** [comment]
Tested on staging. For now it covers what we want from it. Let's see if we receive any requests for improvements.
